// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int lower = 0;
		int bigger = 0;
		int length = Integer.parseInt(args[0]);
		for (int i = 0; i < length; i++) {
			if (Math.random() > 0.5) {
				bigger++;
				} else {
				lower++;
				}
		}
		System.out.println("> 0.5: " + bigger + " times");
		System.out.println("<= 0.5: " + lower + " times");
		if (lower > 0)
		{double ratio = (double) bigger / lower;
		System.out.println("Ratio: " + ratio + " times");
		}
	}
}
